// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUEuG6GCA7C32VFP97gfqkZkhuKcdrI4',
    appId: '1:217528395311:web:393679835e0c20e72948da',
    messagingSenderId: '217528395311',
    projectId: 'clubquranproject',
    authDomain: 'clubquranproject.firebaseapp.com',
    databaseURL: 'https://clubquranproject-default-rtdb.firebaseio.com',
    storageBucket: 'clubquranproject.firebasestorage.app',
    measurementId: 'G-W28FSCBZ22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi9intZHImW4dXdCYy2QONDIykAzw5DHo',
    appId: '1:217528395311:android:2b887dc2c7253b692948da',
    messagingSenderId: '217528395311',
    projectId: 'clubquranproject',
    databaseURL: 'https://clubquranproject-default-rtdb.firebaseio.com',
    storageBucket: 'clubquranproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALznfc3ee_nAqQ6araZcOitu7SrMCXoRQ',
    appId: '1:217528395311:ios:4b3eb084091761472948da',
    messagingSenderId: '217528395311',
    projectId: 'clubquranproject',
    databaseURL: 'https://clubquranproject-default-rtdb.firebaseio.com',
    storageBucket: 'clubquranproject.firebasestorage.app',
    iosBundleId: 'com.example.clubquranproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALznfc3ee_nAqQ6araZcOitu7SrMCXoRQ',
    appId: '1:217528395311:ios:4b3eb084091761472948da',
    messagingSenderId: '217528395311',
    projectId: 'clubquranproject',
    databaseURL: 'https://clubquranproject-default-rtdb.firebaseio.com',
    storageBucket: 'clubquranproject.firebasestorage.app',
    iosBundleId: 'com.example.clubquranproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkUEuG6GCA7C32VFP97gfqkZkhuKcdrI4',
    appId: '1:217528395311:web:8532fd735f1e37972948da',
    messagingSenderId: '217528395311',
    projectId: 'clubquranproject',
    authDomain: 'clubquranproject.firebaseapp.com',
    databaseURL: 'https://clubquranproject-default-rtdb.firebaseio.com',
    storageBucket: 'clubquranproject.firebasestorage.app',
    measurementId: 'G-0GF553HWLP',
  );

}